version: 1.0.0.{build}
os: Visual Studio 2015 RC
assembly_info:
  patch: true
  file: src\AssemblyInfo.Shared.cs
  assembly_version: 1.0.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  verbosity: minimal
