version: 0.1.0.{build}
os: Visual Studio 2015 RC
init:
- ps: $Env:Path = "${Env:ProgramFiles(x86)}\MSBuild\14.0\Bin;${Env:Path}"
assembly_info:
  patch: true
  file: src\AssemblyInfo.Shared.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  HarshPointTestUrl:
    secure: la+SCbMXpAZIZMxu46R9T4qKSdvEtvAHwfUBln2ip4+I9HV4/Rw8800MEVtAfaZ+tnIIo7fZYR4Dv1JTfiR0WQ==
  HarshPointTestUser:
    secure: dFT8d/aQmRHTUx2EitgBamM8JR4ROkPqsU3NexYBiyc/lXY+mRuaNVAuBZwgSD1u
  HarshPointTestPassword:
    secure: VVX16YC4fowxRtF6GaK6Tw==
  HarshPointTestAuth:
    secure: /aPy/TNRcKlV67mllpvM6ZXAoCLkFaKR3HfBb5+n1gI=
build:
  verbosity: minimal
