version: 0.1.{build}-{branch}
os: Visual Studio 2015
assembly_info:
  patch: true
  file: src\AssemblyInfo.Shared.cs
  assembly_version: 1.0.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  HarshPointTestUrl:
    secure: QIbkFa0+qZZkjxDEpovdCOLFYIv+fC6oTSO47Ece4L7JcZx0IqO/w/5gIgJb2JixO0hWQ85U0Cvc0NXMFuvJzA==
  HarshPointTestAuth:
    secure: /JwoCjOxTFwB6posRe9VZZ5N9l4Gw5QyMhckurzBwiU=
  HarshPointTestPassword:
    secure: Z8RcawfKTnTUuNEes2/aOi2en0hyOH8kqn/UQ7IYUyc=
  HarshPointTestUser:
    secure: AvfmFNR1U4uK+CYGYWnuA3frFktaO2/gAEmkBC6jVV4Z9RXL5I+qu+mNvJBbHbrh
  CoverityProjectToken:
    secure: hc59+7cj0LBVUtYH1ssKcYHAsuVE9DbMG7YJl235mHY=
  CoverityNotificationEmail:
    secure: umuF9aSZzRig6SY8QZWWJGrq8gdwjO8lUXfC2JZ/XqY=
nuget:
  disable_publish_on_pr: true
build_script:
- ps: '& .\Invoke-CoverityBuild.ps1'
deploy:
- provider: Environment
  name: MyGet HarshPoint-dev
  on:
    branch: development