//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarshPoint.ShellployGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HarshPoint.ShellployGenerator.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; already exists..
        /// </summary>
        internal static string CodeDomExtensions_FieldExists {
            get {
                return ResourceManager.GetString("CodeDomExtensions_FieldExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property getter is not empty..
        /// </summary>
        internal static string CodeDomExtensions_PropertyGetterNotEmpty {
            get {
                return ResourceManager.GetString("CodeDomExtensions_PropertyGetterNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name is not set..
        /// </summary>
        internal static string CodeDomExtensions_PropertyNameNotSet {
            get {
                return ResourceManager.GetString("CodeDomExtensions_PropertyNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property setter is not empty..
        /// </summary>
        internal static string CodeDomExtensions_PropertySetterNotEmpty {
            get {
                return ResourceManager.GetString("CodeDomExtensions_PropertySetterNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified name &apos;{0}&apos; is reserved..
        /// </summary>
        internal static string CommandBuilder_ReservedName {
            get {
                return ResourceManager.GetString("CommandBuilder_ReservedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no ICommandBuilder for the specified provisioner type &apos;{0}&apos;..
        /// </summary>
        internal static string CommandBuilderContext_NoBuilder {
            get {
                return ResourceManager.GetString("CommandBuilderContext_NoBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to nest one CommandParameterSynthesized in another..
        /// </summary>
        internal static string CommandParameterSynthesized_AttemptedToNest {
            get {
                return ResourceManager.GetString("CommandParameterSynthesized_AttemptedToNest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is set to use both fixed and default value..
        /// </summary>
        internal static string ShellployCommandBuilder_Fixed_and_default {
            get {
                return ResourceManager.GetString("ShellployCommandBuilder_Fixed_and_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate properties defined..
        /// </summary>
        internal static string ShellployCommandBuilder_Overlaps {
            get {
                return ResourceManager.GetString("ShellployCommandBuilder_Overlaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is already defined..
        /// </summary>
        internal static string ShellployCommandBuilder_PropertyChildrenAlreadyDefined {
            get {
                return ResourceManager.GetString("ShellployCommandBuilder_PropertyChildrenAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code compile unit does not contain any type declarations..
        /// </summary>
        internal static string SourceFileWriter_NoTypeDefined {
            get {
                return ResourceManager.GetString("SourceFileWriter_NoTypeDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output directory is a file..
        /// </summary>
        internal static string SourceFileWriter_OutputDirectoryIsFile {
            get {
                return ResourceManager.GetString("SourceFileWriter_OutputDirectoryIsFile", resourceCulture);
            }
        }
    }
}
